apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ministryofjustice/cloud-platform-helloworld-ruby
    newTag: "1.1"