# build.yml
on:
  push:
    paths:
    - "*.rb"
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - main          # triggers on pushes that contain changes in master

name: Build and Push an Image to ECR

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: eu-west-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: ${{ secrets.ECR_URL }}:${{ github.sha }}

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t helloworld .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: helloworld
          image: ${{ secrets.ECR_NAME }}:${{ github.sha }}
    # Set image tag in kustomization

      - name: Set image tag
        run: |
            cd kustomize
            kustomize edit set image $CONTAINER_IMAGE
            cat kustomization.yaml
      - name: Set image tag
        run: |
            cd helm_deploy
            kustomize edit set image $CONTAINER_IMAGE
            cat kustomization.yaml
      - name: Commit kustomization
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -a -m "Push Image with commit :${{ github.sha }}"
      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
            force: true       
